### ISSUE TITLE
Unable to create a CR for BAW Authoring with BAI option

### ISSUE THREAD

**Issue by dcavanau** [apollo-business-automation/ibm-cp4ba-enterprise-deployment#25]
**Describe the bug**
Failed to create a CR with BAW Authoring and BAI enabled.

**To Reproduce**
1. I used the cert-k8s-22.0.1.tar from the ibm-cp-automation-4.0.1.tar to generate a sample CR to determine the patterns and optional components enable in the Apollo-one-shot.configMap. 
2. The following patterns and optional components were generated by the cp4a-deployment.sh:3. 
   ` sc_deployment_patterns: "foundation,workflow"`
    `sc_optional_components: "bai,baw_authoring,cmis"`
3. The Apollo One Shot config map was modified as per the attached file.
4. The log file from the Apollo One Shot deployment job pod is attached showing the error. The CR is not generated.

**Expected behavior**
A CR should be generated.

\**Additional context**
[Apollo-One-Shot-Config-Map.txt](https://github.com/apollo-business-automation/ibm-cp4ba-enterprise-deployment/files/9327811/Apollo-One-Shot-Config-Map.txt)
[apollo-one-shot-install-8fkhw-7fbt2-apollo-one-shot.log](https://github.com/apollo-business-automation/ibm-cp4ba-enterprise-deployment/files/9328541/apollo-one-shot-install-8fkhw-7fbt2-apollo-one-shot.log)

**Comment by jandusek4** [comment]
This is caused by missing content pattern as it is mandatory for BAW Authoring based on https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/22.0.2?topic=deployment-capabilities-production-deployments#concept_c2l_1ks_fnb__baw
