### ISSUE TITLE
Wrong healthcheck URLs for pgAdmin Deployment config

### ISSUE THREAD

**Issue by P-147** [apollo-business-automation/ibm-cp4ba-enterprise-deployment#29]
Hello guys, 
3 days after installing the last version of Apollo (full capability install), I had a "storage" related problem this morning linked to the way your `pgadmin` Deployment does healthchecks, could you update it? 🙂

## The Problem

I was warned this morning by the team managing the storage of my cluster (I use a Spectrum Scale) that I reached the max number of inodes on one of my PVC named `pgadmin-data`.
After some investigation, we found out that the `pgadmin` pod kept creating thousand files on the PVC.

After purging the content of the folder `/var/lib/pgadmin/sessions` (containing at the time around 58k session files ...), I noticed that 24 session files were created per minute.

After checking the Pod YAML definition, I found the culprits : the livenessProbe & readinessProbe defined on the Deployment config. Both probes were running every 10 sec, doing a query on the base URL of the pgAdmin UI.

This is where it becomes a problem: the baseUrl of the pgAdmin UI generates a session cookie/file for each new connection. As probes do not store HTTP cookies... a cookie/file is generated for each probe execution on the PVC.
This means around 34560 files gets generated for nothing each day.

## The Solution

I searched a little on the web, and it seems the pgAdmin UI exposes a `/misc/ping` url that can safely be used to do health checks! (it does not generate session cookies) ([example here](https://github.com/helm/charts/issues/19690#issuecomment-581476341))

Updating the "path" properties of both livenessProbe & readinessProbe from `/` to `/misc/ping` in your deployment should fix the issue 😉 (cf. here, on lines 53 & 59)
https://github.com/apollo-business-automation/ibm-cp4ba-enterprise-deployment/blob/8579294291e5bc81ec9ce3feeece65fd19210921/scripts/roles/pgadmin/templates/deployment.yaml.j2#L49-L60

**Bonus**: Another improvement possible: set a higher threshold for the livenessProbe [as recommended by the Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#:~:text=A%20common%20pattern%20for%20liveness%20probes%20is%20to%20use%20the%20same%20low%2Dcost%20HTTP%20endpoint%20as%20for%20readiness%20probes%2C%20but%20with%20a%20higher%20failureThreshold.%20This%20ensures%20that%20the%20pod%20is%20observed%20as%20not%2Dready%20for%20some%20period%20of%20time%20before%20it%20is%20hard%20killed.).

**Comment by thomas-dussouillez** [comment]
thank you for the solution !
