### ISSUE TITLE
Adjust waiting to real numbers using playbook runs, actual time

### ISSUE THREAD

**Issue by ondrejsvec-ibm** [apollo-business-automation/ibm-cp4ba-enterprise-deployment#9]
**Is your feature request related to a problem? Please describe.**
Adjust waiting to real numbers using playbook runs, actual time

**Describe the solution you'd like**
not clear

**Comment by ondrejsvec-ibm** [comment]
@jandusek4 Can you please clarify a bit what is the todo/issue about?

**Comment by jandusek4** [comment]
@ondrejsvec-ibm The goal is to observe real deployments and adjust ansible waiting times. As an example, if DB2 should/is typically up and running after 10 minutes, we should wait for like 15 minutes and not 60 so if the deployment would fail, it should fail fast.
Problem I see here is that this doesn't count with slow PVC binding which occurs e.g. on ROKS StorageClasses. In this case, maybe we should just wait for 60minutes always.
